### ISSUE TITLE
Unknown request URI

### ISSUE THREAD

**Issue by SteelzZ** [GoogleCloudPlatform/gcloud-golang#209] opened 2016-02-08 18:58 UTC
I have gcloud in docker container and running pubsub emulator inside.

Trying to create topic :
```
ctx := context.Background()
client := oauth2.NewClient(ctx, nil)
service, _ := pubsub.New(client)
service.BasePath = "http://192.168.99.100:8082/"
topic, _ := service.Projects.Topics.Create(fullTopicName("xxxx", "some-topic"), &pubsub.Topic{}).Do()
```
As response i get 404:
```
googleapi: got HTTP response code 404 with body: Not Found
```

And in pubsub logs i see:
```
pubsub] Feb 08, 2016 6:02:16 PM com.google.cloud.pubsub.testing.v1.GrpcServer$3 operationComplete
[pubsub] INFO: Adding handler(s) to newly registered Channel.
[pubsub] Feb 08, 2016 6:02:16 PM com.google.cloud.pubsub.testing.v1.HttpVersionRoutingHandler channelRead
[pubsub] INFO: Detected non-HTTP/2 connection.
[pubsub] Feb 08, 2016 6:02:16 PM com.google.cloud.pubsub.testing.v1.NotFoundHandler handleRequest
[pubsub] INFO: Unknown request URI: http://192.168.99.100:8082/v1/projects/xxxx/topics/some-topic?alt=json
```

But if do a pure curl request, it works:
```
curl -X PUT http://192.168.99.100:8082/v1/projects/xxxx/topics/some-topic?alt=json
{
  "name": "projects/xxxx/topics/some-topic"
}
```

Was trying to dig in and figured out that disabling [this](https://github.com/google/google-api-go-client/blob/master/googleapi/googleapi.go#L309) solves issue, but not sure if that is a problem. 

Perhaps it relates somehow to [this](https://github.com/golang/go/issues/4860) golang issue ? And [this](https://github.com/google/google-api-go-client/blob/master/googleapi/googleapi.go#L289) check here ?

Ideas?

**Comment by broady** [comment] 2016-03-17 21:51
Dupe of #210.

**Closed by broady** 2016-03-17 21:51 UTC
