### ISSUE TITLE
bigquery: streaming inserts

### ISSUE THREAD

**Issue by nightlyone** [GoogleCloudPlatform/gcloud-golang#222] opened 2016-03-13 13:00 UTC
bigquery supports streaming inserts, which are not yet supported by this API.

Added an issue, so interested parties can start working by providing possible designs here.

**Comment by mcgreevy** [comment] 2016-03-16 05:51
I have some code written to do this which has been on the back burner for a little while.  I intend to resurrect it soon.

**Comment by mcgreevy** [comment] 2016-04-29 04:08
Duplicate of #189.

**Closed by mcgreevy** 2016-04-29 04:08 UTC
Labels: bigquery
