### ISSUE TITLE
travis builds failing

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/gcloud-golang#138] opened 2015-06-18 18:17 UTC
https://travis-ci.org/GoogleCloudPlatform/gcloud-golang/builds

Are you still using travis for CI, or are you using something else?

**Comment by gmlewis** [comment] 2015-06-18 18:51
Yes, we are.  I'll investigate.

**Comment by gmlewis** [comment] 2015-06-18 19:03
It looks like [one commit](https://github.com/GoogleCloudPlatform/gcloud-golang/commit/c29b8a96e706d555f7ad20f4b60eacf799b38be4) broke the [Go:tip](https://travis-ci.org/GoogleCloudPlatform/gcloud-golang/jobs/65350777) build and [another commit](https://github.com/GoogleCloudPlatform/gcloud-golang/commit/d3d1bf0824dc807dcad25d3696b634cc8599ad60) broke the [Go:1.4](https://travis-ci.org/GoogleCloudPlatform/gcloud-golang/jobs/66976096) build.
I've asked the authors of those commits to investigate.

**Comment by dsymonds** [comment] 2015-07-19 23:41
Travis appears to be using a broken tip, over two weeks old. The real tip works fine and doesn't break in those ways.

**Comment by gmlewis** [comment] 2015-07-20 17:09
Now locally I get this error:
```
--- FAIL: TestACL-12 (3.31s)
	integration_test.go:310: Cleanup deletion of acl1
	integration_test.go:310: Cleanup deletion of acl2
	integration_test.go:251: Writing acl1
	integration_test.go:251: Writing acl2
	integration_test.go:292: Expected to find an ACL rule for jbd@google.com user, but not found
	integration_test.go:295: Error while deleting bucket ACL rule: storage: error deleting bucket ACL rule for bucket "bucketname", entity "user-jbd@google.com": googleapi: Error 404: Not Found, notFound
FAIL
FAIL	google.golang.org/cloud/storage	11.666s
```
I'll work on it.

**Comment by gmlewis** [comment] 2015-07-20 18:35
This error appears to be a regression in the Cloud Storage API.  Filed a bug with the Storage team.

**Comment by gmlewis** [comment] 2015-07-21 03:46
Travis Go 1.4 tests are now passing.  I filed a separate issue for the commented-out PutBucketACLRule test.  Closing issue.

**Closed by gmlewis** 2015-07-21 03:46 UTC
