### ISSUE TITLE
Not able to make a  Newly created file public on Google Cloud Storage Go runtime Client API

### ISSUE THREAD

**Issue by Karthic-Hackintosh** [GoogleCloudPlatform/gcloud-golang#122] opened 2015-03-25 07:11 UTC
Here is the piece of code which i have used to write a string into a file in google cloud storage from Go Runtime 

    wc := storage.NewWriter(d.ctx, bucket, fileName)
    wc.ContentType = "text/plain"
    wc.ACL = []storage.ACLRule{{storage.AllUsers, storage.RoleReader}}
    if _, err := wc.Write([]byte(myData)); err != nil {
            d.errorf("createFile: unable to write data to bucket %q, file %q: %v", bucket, fileName, err)
            return
    }
But i want the uploaded file to be public so that i anybody could potentially access it with the public link , its not happening ..How do i achieve the goal of making the file public

**Comment by gmlewis** [comment] 2015-03-25 07:35
I just confirmed that this is broken... this code used to work and the file would be shared publicly.
I don't have time to investigate this further at the moment...
Something has changed but I don't know what.
I will investigate this next week.  Sorry for the delay.

**Comment by Karthic-Hackintosh** [comment] 2015-03-25 07:40
@gmlewis Thank you for your response. We will now wait to hear from you, as we have spent considerable time trying to get this to work. At least we know it was not something we were doing wrong now. 

Would you know if this problem exists on the Java or Python runtime within Google Cloud, or this is just in the Go Runtime stack?

**Comment by gmlewis** [comment] 2015-03-25 16:32
I do not know, as I have not tested those runtimes.  It would be an excellent experiment, though... to try and narrow down the issue.  If those also exhibit the problem, then we are dealing with a bug in the GCS service itself.

Another interesting experiment is to use the google-api-go-client storage:v1 library directly to create the file and see if the results are the same.  If that library can create publicly sharable files, then the problem most likely is in this Go veneer client library.

**Comment by Karthic-Hackintosh** [comment] 2015-03-28 08:20
We tested on Java Runtime , and it works ! Unfortunately we have to move to Java Runtime till this issue is fixed . Will be waiting to know about the status of this issue

**Comment by jseeley78** [comment] 2015-04-06 17:37
Having this same issue; I would not expect the "storage.AllUsers" to give public access however as that just maps to the 'allUsers' ACL permission; According to the docs->
'allUsers does not make objects publicly accessible'

I had assumed I could send a different ACL permission like, ''public-read' but that isn't working either... 
Is this truly not possible with the golang API?

**Comment by jseeley78** [comment] 2015-04-07 22:56
It seems this actually does work, but if you only set the "allUsers" permission then you can't tell that there is actually a public link. I could confirm it worked when I set other permissions too->

wc.ACL = []gstorage.ACLRule{
		{Entity: gstorage.AllUsers, Role: storage.RoleReader},
		{Entity: gstorage.ACLEntity("project-owners-"+ProjectNumber), Role: storage.RoleOwner},
		{Entity: gstorage.ACLEntity("project-editors-"+ProjectNumber), Role: storage.RoleOwner},
		{Entity: gstorage.ACLEntity("project-viewers-"+ProjectNumber), Role: storage.RoleOwner},
	}

**Comment by bradfitz** [comment] 2015-05-11 00:02
Yes, this is a bug in Google's web frontend for Cloud Storage. It doesn't have permission itself to know whether it's public or not.

The workaround is to give it permission to notice that it's public.

**Comment by gmlewis** [comment] 2015-05-19 14:14
What if we made this simpler by providing:
```go
func storage.PublicACL(projectNumber string) []storage.ACLRule {...}
```
that returns the example shown [two comments prior](https://github.com/GoogleCloudPlatform/gcloud-golang/issues/122#issuecomment-90753260)?
@rakyll - SGTY?

**Comment by bradfitz** [comment] 2015-05-19 14:15
@gmlewis, that means we're adding new API (that we have to maintain forever and users will have to see in godoc forever), just to work around a bug elsewhere (the GCS web UI). That seems less than ideal.

**Comment by rakyll** [comment] 2015-05-19 16:44
@gmlewis, I agree with Brad that we shouldn't introduce new APIs as bug workarounds. We can just give them a link to this issue until the web UI bug is fixed.

**Comment by rsc** [comment] 2015-08-07 15:27
The comment from March 28 says the Java API works. For @Karthic-Hackintosh can you post the snippet of Java code you are using that works? 

For @gmlewis, @bradfitz, @rakyll, @okdave, why does the Java API work and Go does not? Is the Java API fixing up the call? If so Go could do that without introducing new API.

**Comment by Karthic-Hackintosh** [comment] 2015-08-07 19:39
@gmlewis   , @rakyll , @bradfitz  , Isnt this issue fixed yet ??   We are planning to move our Java pieces to Go , If this issue isnt fixed yet then we'll halt the port to Golang on AppEngine for a while . 
@rsc  , the following code anippet in Java helps to make the uploaded file public 
```GcsFileOptions ruleForWrite = new GcsFileOptions.Builder().acl("public_read").mimeType("text/plain").build() ```

**Comment by gmlewis** [comment] 2015-08-07 19:48
Isn't the workaround shown above in the April 7 comment sufficient to unblock you until this is officially fixed?

**Comment by gmlewis** [comment] 2015-08-11 00:08
It turns out that having `wc.ACL = []storage.ACLRule{{storage.AllUsers, storage.RoleReader}}` is sufficient to make the file publicly accessible.

The Cloud Console, however, is only displaying the "Shared Publicly" checkmark if the workaround in the April 7 comment is used.  I'm filing a bug with the Cloud Console team and am closing this issue as Working As Intended.

**Comment by gmlewis** [comment] 2015-08-11 18:03
I've learned that the use of PredefinedACLs can improve the situation here, so I'm re-opening the bug and will put together a PR.

**Comment by gmlewis** [comment] 2015-08-11 19:34
I've tested out the use of PredefinedAcl ("publicRead") from storage:v1 and it does not solve the problem. The Cloud Developers Console team is aware of the issue and is working on a solution.

Meanwhile, using `wc.ACL = []storage.ACLRule{{storage.AllUsers, storage.RoleReader}}` does make the file publicly accessible and if you want the checkmarks to show up as "Shared Publicly" in the Cloud Developers Console, then you can add the workaround from April 7.

Closing issue again.

**Closed by gmlewis** 2015-08-11 19:34 UTC
Labels: storage

**Comment by RobWelain** [comment] 2017-04-26 15:45
Great! Thanks!
