### ISSUE TITLE
CI failed in master branch

### ISSUE THREAD

**Issue by laco0416** [GoogleCloudPlatform/gcloud-golang#173] opened 2015-09-17 04:06 UTC
CI status is error.

https://travis-ci.org/GoogleCloudPlatform/gcloud-golang

Please keep `master` branch ALWAYS green.

**Comment by vvakame** [comment] 2015-09-17 04:16
Our product can't build now...
We use appengine/go.
appengine/go is go 1.4, not go 1.5.
1.4 not supported vendor directory...

**Comment by broady** [comment] 2015-09-17 05:14
dupe of #171

**Closed by broady** 2015-09-17 05:14 UTC
