### ISSUE TITLE
cloud storage preconditions missing

### ISSUE THREAD

**Issue by suau** [GoogleCloudPlatform/gcloud-golang#191] opened 2015-11-30 07:38 UTC
There is no way to include preconditions when creating/updating an object in the golang library.
This seems crucial for not accidentally overwriting data.

It is available for the Java client library (I couldn't find the proper page for general Preconditions anymore):
https://cloud.google.com/storage/docs/object-versioning#_ConditionalUpdate

**Comment by sbaileyms** [comment] 2015-11-30 15:00
You can do it by also including the storage/API/v1 package (label it rawStorage) and the use the Patch function.

**Comment by suau** [comment] 2015-11-30 15:32
Thanks for the tip! I'm wondering what are the plans/use cases for these 2 client libraries ? I looked into both and both seem to use http, just one with protobuf the other with json. (I mistakenly assumed the cloud package one would use direct RPC like the appengine/datastore).

**Comment by okdave** [comment] 2015-12-04 02:51
This is a duplicate of #188.

**Closed by okdave** 2015-12-04 02:51 UTC
